apiVersion: v2
name: open-webui
version: 1.0.0
appVersion: 1.5.1
home: https://www.openwebui.com/
icon: https://raw.githubusercontent.com/open-webui/open-webui/main/static/favicon.png
description: 'Open WebUI: A User-Friendly Web Interface for Chat Interactions'
keywords:
  - llm
  - chat
  - web-ui
  - open-webui
sources:
  - https://github.com/open-webui/open-webui
  - https://github.com/NotYuSheng/open-webui_secure
  - https://github.com/NotYuSheng/open-webui_webwork
