nameOverride: ""
namespaceOverride: ""

clusterDomain: cluster.local

annotations: {}
podAnnotations: {}
podLabels: {}

replicaCount: 1
strategy: {}

image:
  repository: image-registry.openshift-image-registry.svc:5000/open-webui/open-webui_webwork
  tag: "v1.5.1-6b044964"
  pullPolicy: IfNotPresent

imagePullSecrets: []

resources: {}

copyAppData:
  resources: {}

ingress:
  enabled: true
  host: open-webui.apps-crc.testing

persistence:
  enabled: true
  size: 2Gi
  existingClaim: ""
  subPath: ""
  accessModes:
    - ReadWriteOnce
  storageClass: ""
  selector: {}
  annotations: {}

nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []
hostAliases: []

service:
  type: ClusterIP
  annotations: {}
  port: 80
  containerPort: 8080
  nodePort: ""
  labels: {}
  loadBalancerClass: ""

volumeMounts:
  initContainer: []
  container: []

podSecurityContext: {}
containerSecurityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false

extraEnvVars:
  - name: WEBUI_AUTH
    value: "False"

keycloak:
  enabled: true

  # TODO: Configure this section with Starlabs
  clientId:       "webui-client"
  clientSecret:   "HS5Qc5cTfCrt04h5f3gEFtyGkYRZfWul"

  # Point at your managed Keycloak instance:
  protocol:       "https"
  host:           "auth.mycorp.com"
  port:           "443"
  realm:          "myrealm"

  # Optional widget/display settings
  providerName:   "Keycloak"
  enableSignup:   false
