nameOverride: ""
namespaceOverride: ""

ollama:
  enabled: false

pipelines:
  enabled: false

tika:
  enabled: false

ollamaUrls: []
ollamaUrlsFromExtraEnv: false

websocket:
  enabled: false
  manager: redis
  url: redis://open-webui-redis:6379/0
  redis:
    enabled: false  # disable deploying Redis too if websocket is off

redis-cluster:
  enabled: false

clusterDomain: cluster.local

annotations: {}
podAnnotations: {}
podLabels: {}
replicaCount: 1
strategy: {}

image:
  repository: ghcr.io/notyusheng/open-webui_secure
  tag: "v1.4"  # TODO: Change this to newest version
  pullPolicy: "Never"

serviceAccount:
  enable: true
  name: ""
  annotations: {}
  automountServiceAccountToken: false

imagePullSecrets: []

livenessProbe: {}
readinessProbe: {}
startupProbe: {}

resources: {}

copyAppData:
  resources: {}

managedCertificate:
  enabled: false

ingress:
  enabled: false

persistence:
  enabled: true
  size: 2Gi
  existingClaim: ""
  subPath: ""
  accessModes:
    - ReadWriteOnce
  storageClass: ""
  selector: {}
  annotations: {}

nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []
hostAliases: []

service:
  type: ClusterIP
  annotations: {}
  port: 80
  containerPort: 8080
  nodePort: ""
  labels: {}
  loadBalancerClass: ""

enableOpenaiApi: false
openaiBaseApiUrl: ""
openaiBaseApiUrls: []

extraEnvVars: []

volumeMounts:
  initContainer: []
  container: []

extraInitContainers: []
volumes: []

podSecurityContext: {}
containerSecurityContext: {}

extraResources: []
