nameOverride: ""
namespaceOverride: ""

clusterDomain: cluster.local

annotations: {}
podAnnotations: {}
podLabels: {}

replicaCount: 1
strategy: {}

image:
  repository: ghcr.io/notyusheng/open-webui_webwork
  tag: "v1.5.1"
  pullPolicy: "Never"

serviceAccount:
  enable: true
  name: ""
  annotations: {}
  automountServiceAccountToken: false

imagePullSecrets: []

resources: {}

copyAppData:
  resources: {}

managedCertificate:
  enabled: false

ingress:
  enabled: false

persistence:
  enabled: true
  size: 2Gi
  existingClaim: ""
  subPath: ""
  accessModes:
    - ReadWriteOnce
  storageClass: ""
  selector: {}
  annotations: {}

nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []
hostAliases: []

service:
  type: ClusterIP
  annotations: {}
  port: 80
  containerPort: 8080
  nodePort: ""
  labels: {}
  loadBalancerClass: ""

volumeMounts:
  initContainer: []
  container: []
